server:
  port: 8089
spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5431/autenticacionproduct
    username: nttdata
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
#    enabled: false

jwt:
  secret: secret

admin-paths:
  paths:
    - uri: "/api-projectsales/v1/producto"
      method: "POST"
    - uri: "/api-projectsales/v1/producto"
      method: "PUT"
    - uri: "/api-projectsales/v1/producto/{1}[1-9]+[0-9]*"
      method: "DELETE"
    - uri: "/api-projectsales/v1/producto-check/{1}[1-9]+[0-9]*"
      method: "GET"