apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigatewayproduct
  labels:
    app: apigatewayproduct
spec:
  replicas: 1
  template:
    metadata:
      name: apigatewayproduct
      labels:
        app: apigatewayproduct
    spec:
      containers:
        - name: apigatewayproduct
          image: sergiogf/apigatewayproduct:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: apigatewayproduct