apiVersion: apps/v1
kind: Deployment
metadata:
  name: validarproductocheck
  labels:
    app: validarproductocheck
spec:
  replicas: 1
  template:
    metadata:
      name: validarproductocheck
      labels:
        app: validarproductocheck
    spec:
      containers:
        - name: validarproductocheck
          image: sergiogf/validarproducto:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: validarproductocheck