apiVersion: apps/v1
kind: Deployment
metadata:
  name: validarproducto
  labels:
    app: validarproducto
spec:
  replicas: 1
  template:
    metadata:
      name: validarproducto
      labels:
        app: validarproducto
    spec:
      containers:
        - name: validarproducto
          image: sergiogf/validarproducto:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: validarproducto