apiVersion: v1
kind: Service
metadata:
  #Importante tiene que tener el mismo name que el microservicios del yml
  name: validarproductocheck
spec:
  selector:
    app: validarproductocheck
  ports:
    - port: 8081
      targetPort: 8085
  type: NodePort