server:
  port: 8092

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        #id interno en el yml de aqui
        - id: cliente
          #lb://CLIENTE = viene de Nombre de EUREKA o del properties o yml
          uri: lb://CLIENTE
          predicates:
            #Path= despues debe ir la ruta del Controller dentro del @RequestMapping: api-projectsales/v1/cliente
            - Path=/api-projectsales/v1/cliente/**
        #id interno en el yml de aqui
        - id: validar
          #lb://validar = viene de Nombre de EUREKA o del properties o yml
          uri: lb://VALIDARCLIENTECHECK
          predicates:
            #Path= despues debe ir la ruta del Controller dentro del @RequestMapping: api-projectsales/v1/cliente

            - Path=/api-projectsales/v1/cliente-check/**

          #id interno en el yml de aqui
        - id: producto
            #lb://validar = viene de Nombre de EUREKA o del properties o yml
          uri: lb://PRODUCTO
          predicates:
              #Path= despues debe ir la ruta del Controller dentro del @RequestMapping: api-projectsales/v1/cliente

              - Path=/api-projectsales/v1/producto/**
            #id interno en el yml de aqui
        - id: detallepediddo
                #lb://validar = viene de Nombre de EUREKA o del properties o yml
          uri: lb://PRODUCTO
          predicates:
                  #Path= despues debe ir la ruta del Controller dentro del @RequestMapping: api-projectsales/v1/cliente

              - Path=/api-projectsales/v1/detallepedido/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true