apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - port: 8090
      #PUERTO EXTERNO CMD O HTTP PROPERTIES CLIENTEFEIGN
      targetPort: 8090
      #PUERTO INTERNO MICROSERVICIOS
  type: LoadBalancer