INSERT INTO ciudad (id_ciudad,provincia,departamento,fecha_Creacion) VALUES (1,'Trujillo','La Libertad','2022-07-25') ON CONFLICT (id_ciudad) DO NOTHING;
INSERT INTO ciudad (id_ciudad,provincia,departamento,fecha_Creacion) VALUES (2,'Amazonas','Bagua','2022-07-25') ON CONFLICT (id_ciudad) DO NOTHING;
INSERT INTO ciudad (id_ciudad,provincia,departamento,fecha_Creacion) VALUES (3,'Ancash','Huaraz','2022-07-25') ON CONFLICT (id_ciudad) DO NOTHING;
INSERT INTO ciudad (id_ciudad,provincia,departamento,fecha_Creacion) VALUES (4,'Apurimac','Andahuaylas','2022-07-25') ON CONFLICT (id_ciudad) DO NOTHING;
INSERT INTO ciudad (id_ciudad,provincia,departamento,fecha_Creacion) VALUES (5,'Arequipa','Arequipa','2022-07-25') ON CONFLICT (id_ciudad) DO NOTHING;
INSERT INTO ciudad (id_ciudad,provincia,departamento,fecha_Creacion) VALUES (6,'Ayacucho','Lucanas','2022-07-25') ON CONFLICT (id_ciudad) DO NOTHING;
INSERT INTO ciudad (id_ciudad,provincia,departamento,fecha_Creacion) VALUES (7,'Cajamarca','Cajabamba','2022-07-25') ON CONFLICT (id_ciudad) DO NOTHING;
INSERT INTO ciudad (id_ciudad,provincia,departamento,fecha_Creacion) VALUES (8,'Cusco','Anta','2022-07-25') ON CONFLICT (id_ciudad) DO NOTHING;
INSERT INTO ciudad (id_ciudad,provincia,departamento,fecha_Creacion) VALUES (9,'Huancavelica','Angaraes','2022-07-25') ON CONFLICT (id_ciudad) DO NOTHING;
INSERT INTO ciudad (id_ciudad,provincia,departamento,fecha_Creacion) VALUES (10,'Huanuco','Dos de Mayo','2022-07-25') ON CONFLICT (id_ciudad) DO NOTHING;
INSERT INTO ciudad (id_ciudad,provincia,departamento,fecha_Creacion) VALUES (11,'Ica','Chincha','2022-07-25') ON CONFLICT (id_ciudad) DO NOTHING;
INSERT INTO ciudad (id_ciudad,provincia,departamento,fecha_Creacion) VALUES (12,'Junin','Satipo','2022-07-25') ON CONFLICT (id_ciudad) DO NOTHING;