server:
  port: 8084
spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://postgres:5432/producto
    username: nttdata
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #create-drop
      #update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  #sql:
  #  init:
  #    mode: always
  #    schema-locations: classpath:bd/tablas.sql
  #    data-locations: classpath:bd/data.sql
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
#    enabled: false
  instance:
    prefer-ip-address: true
#CIRCUR BREAKER OPCIONAL
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
#CIRCUR BREAKER  REINTENTOS TRABAJAN JUNTOS
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      validarproductoCB:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    retry-aspect-order: 2
    instances:
      validarproductoRetry:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 5s
